/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
#include "string.h"
void look_file_content_slice_1(char *input_filename)
{
  *(input_filename + 2) = (char)'b';
  /*@ \slicing::slice_preserve_expr input_filename; */ ;
  /*@ \slicing::slice_preserve_stmt ; */
  FILE *input_file = fopen((char const *)input_filename,"r");
  return;
}

/*@ requires valid_read_string(param0);
    requires valid_read_string(param1);
    requires valid_read_string(format);
 */
int sprintf_va_1(char * restrict s, char const * restrict format,
                 char *param0, char *param1);

void main(void)
{
  char input_filename[100];
  char prefix[6] =
    {(char)'i', (char)'n', (char)'p', (char)'u', (char)'t', (char)'\000'};
  char suffix[5] =
    {(char)'.', (char)'t', (char)'x', (char)'t', (char)'\000'};
  sprintf_va_1(input_filename,"%s%s",prefix,suffix);
  look_file_content_slice_1(input_filename);
  return;
}


