Sources:
  - Name: fread
    DstArgs: [0]
  - Name: fgets
    DstArgs: [0]
  - Name: fscanf
    DstArgs: [0]
  - Name: fread
    DstArgs: [0]
  - Name: safe_read
    DstArgs: [1]



Sinks:
  - Name: fwrite
    DstArgs: [0]
  - Name: full_write
    DstArgs: [1]
  - Name: fwrite_unlocked
    DstArgs: [0]
